apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: modelserver2-dec18-3 
  janus-idp.io/tekton: modelserver2-dec18-3
  backstage.io/kubernetes-id: modelserver2-dec18-3
  backstage.io/kubernetes-namespace: modelserver2-dec18-3 
  app.kubernetes.io/part-of: modelserver2-dec18-3
resources: 
- application-dev.yaml