apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: modelserver2-dec18-3-gitops
  description: This is GitOps manifest for modelserver2-dec18-3   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=modelserver2-dec18-3
    # argocd/app-name: modelserver2-dec18-3
    janus-idp.io/tekton: modelserver2-dec18-3 
    backstage.io/kubernetes-id: modelserver2-dec18-3 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental  
