---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: modelserver2-dec18-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: modelserver2-dec18-3 
  name: modelserver2-dec18-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi