kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: modelserver2-dec18-3-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: modelserver2-dec18-3-dsp-job
    namespace: modelserver2-dec18-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modelserver2-dec18-3-imagestream-job-role
